apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # Base64 encoded 'password' for root access
  mysql-database: dGVzdGRi # Base64 encoded 'testdb'
  mysql-user: dGVzdHVzZXI= # Base64 encoded 'testuser'
  mysql-password: dGVzdHBhc3M= # Base64 encoded 'testpass'
