name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (required for cross-platform image builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image and tag it with both 'latest' and a unique tag based on the Git commit SHA
      - name: Build Docker image
        run: |
          TAG=${{ github.sha }}
          docker build -t anasfarooq/calc-app:latest -t anasfarooq/calc-app:${TAG} .

      # Step 5: Push both the 'latest' and unique tagged Docker images to Docker Hub
      - name: Push Docker image
        run: |
          TAG=${{ github.sha }}
          docker push anasfarooq/calc-app:latest
          docker push anasfarooq/calc-app:${TAG}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Pull the Docker image with the latest tag on the VM
      - name: Pull Docker image
        run: |
          docker pull anasfarooq/calc-app:latest

      # Step 5: Run the Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 anasfarooq/calc-app:latest
