apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          ports:
            - containerPort: 80 # Standard HTTP port for PHPMyAdmin
          env:
            - name: PMA_HOST
              value: mysql-service # Reference to the MySQL Service name
            - name: PMA_PORT
              value: "3306" # Port used by the MySQL Service
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user # Non-root MySQL user from the secret
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password # Password for the MySQL user
